### ISSUE TITLE
Please can the charm be updated to support 22.04?

### ISSUE THREAD

**Issue by coreycb** [canonical/charm-lldpd#12]
22.10 support would also be nice as we have openstack bundles that test with 22.04 and 22.10 nova-compute and the subordinate series must match.

**Comment by vernhart** [comment]
The charm seems to function correctly with jammy without any functional changes.

This works:

```
juju deploy ubuntu --series jammy
juju deploy lldpd --series jammy --force
juju add-relation ubuntu lldpd
```

No hook failures.

**Comment by coreycb** [comment]
Sorry just getting back to this. Force unfortunately doesn't work atm, at least with charmhub: https://bugs.launchpad.net/juju/+bug/1996794

**Comment by coreycb** [comment]
Here's a recreate:

$ juju --version
2.9.43-ubuntu-amd64

$ cat jammy-zed.yaml 
series: &series jammy

applications:

  nova-compute:
    charm: ch:nova-compute
    channel: latest/edge

  lldpd:
    charm: cs:lldpd  # same behavior with ch:lldpd also
    options:
      interfaces-regex: 'en*'
      short-name: true

relations:
- - lldpd
  - nova-compute

$ juju deploy --force ./jammy-zed.yaml
Located charm "lldpd" in charm-store, channel stable
Located charm "nova-compute" in charm-hub, channel latest/edge
Executing changes:
- upload charm lldpd from charm-store for series jammy with architecture=amd64
- deploy application lldpd from charm-store on jammy
- upload charm nova-compute from charm-hub for series jammy from channel latest/edge with architecture=amd64
- deploy application nova-compute from charm-hub on jammy with latest/edge
- add relation lldpd - nova-compute
ERROR cannot deploy bundle: cannot add relation between "lldpd" and "nova-compute": cannot add relation "lldpd:juju-info nova-compute:juju-info": principal and subordinate applications' series must match

**Comment by ivoks** [comment]
Hey all

Charm has now moved to charmcraft/charmhub, but it lost the support for NRPE. We'll work on this and once that's done we'll push new charms to charmhub. I'll keep this case open till then.

**Comment by gustavosr98** [comment]
Hi @ivoks,

Would this be pushed to the published charm?
I have the latest/stable rev 9
And I have the following on metadata.yaml (not including Jammy)
https://paste.ubuntu.com/p/CgQCBJSWRg/

This makes me to remove the charm from my machines to avoid any weird issues upgrading from focal to jammy. Woudn't want to add any `--force` during upgrade commands

**Comment by ivoks** [comment]
Hi @gustavosr98

@wolsen and his team have took over ownership of the charm and the code.

**Comment by wolsen** [comment]
22.04 support has been published to the latest/candidate channel.
