### ISSUE TITLE
Test is not working

### ISSUE THREAD

**Issue by xtrusia** [canonical/charm-lldpd#18]
I should move flake8 to to the last line in run_tests. ( or run_tests doesn't run coverage command at all )

even if i do that, I see a lot of errors when I run run_tests.

Is there another way to run tests for this charm?

or do I need to fix(delete) unused tests?

Thanks.

**Comment by wolsen** [comment]
This issue was resolved with https://github.com/canonical/charm-lldpd/pull/20 as the repository was switched to using tox to run tests. Thank you for the bug report and patch!
